/**
 * Ann Arbor / Dexter seed = researched feeds only.
 * NEVER invent Story bodies, events, or showtimes.
 * Browser-blocked calendars stay html/none with a handoff note.
 */
import { withSectionHeaderSeeds } from "@/lib/section-headers";
import type { AppData, Beat, Source } from "@/lib/types";

const beats: Beat[] = [
  { id: "beat_all", name: "All sources", slug: "all", sort: 0 },
  { id: "beat_general", name: "General news", slug: "general-news", sort: 1 },
  { id: "beat_government", name: "Government", slug: "government", sort: 2 },
  { id: "beat_public_safety", name: "Public safety", slug: "public-safety", sort: 3 },
  { id: "beat_schools", name: "Schools", slug: "schools", sort: 4 },
  { id: "beat_transit", name: "Transit", slug: "transit", sort: 5 },
  { id: "beat_events", name: "Events", slug: "events", sort: 6 },
  { id: "beat_shows", name: "Shows", slug: "shows", sort: 7 },
  { id: "beat_arts", name: "Arts", slug: "arts", sort: 8 },
  { id: "beat_business", name: "Business", slug: "business", sort: 9 },
  { id: "beat_social", name: "Social", slug: "social", sort: 10 },
  { id: "beat_sports", name: "Sports", slug: "sports", sort: 11 },
  { id: "beat_hs_sports", name: "High school sports", slug: "high-school-sports", sort: 12 },
  { id: "beat_original", name: "Original", slug: "original", sort: 13 },
];

const sources: Source[] = [
  {
    id: "src_michigandaily",
    name: "Michigan Daily",
    homepage: "https://www.michigandaily.com/",
    feed_url: "https://www.michigandaily.com/feed/",
    pull_method: "rss",
    beat_id: "beat_general",
    enabled: true,
    notes: "Verified RSS. Campus + city. Do not add the sports feed — U-M varsity would drown local.",
    lane: "wire",
    place: "Ann Arbor",
    weight: 2,
  },
  {
    id: "src_michigandaily_news",
    name: "Michigan Daily — News",
    homepage: "https://www.michigandaily.com/",
    feed_url: "https://www.michigandaily.com/news/feed/",
    pull_method: "rss",
    beat_id: "beat_general",
    enabled: true,
    notes: "Verified section RSS.",
    lane: "wire",
    place: "Ann Arbor",
    weight: 2,
  },
  {
    id: "src_aaobserver",
    name: "Ann Arbor Observer",
    homepage: "https://annarborobserver.com/",
    feed_url: "https://annarborobserver.com/feed/",
    pull_method: "rss",
    beat_id: "beat_general",
    enabled: true,
    notes: "Verified RSS. Do not use observer.com (unrelated NYC publication).",
    lane: "wire",
    place: "Ann Arbor",
    weight: 2,
  },
  {
    id: "src_wemu",
    name: "WEMU 89.1",
    homepage: "https://www.wemu.org/",
    feed_url: "https://www.wemu.org/news.rss",
    pull_method: "rss",
    beat_id: "beat_general",
    enabled: true,
    notes: "Verified news.rss. index.rss is empty — do not use it.",
    lane: "wire",
    place: "Washtenaw",
    weight: 2,
  },
  {
    id: "src_suntimes",
    name: "The Sun Times News",
    homepage: "https://thesuntimesnews.com/",
    feed_url: "https://thesuntimesnews.com/feed/",
    pull_method: "rss",
    beat_id: "beat_general",
    enabled: true,
    notes: "Dexter / Chelsea / Saline weeklies. Reserved Dexter Around slots.",
    lane: "wire",
    place: "Dexter",
    weight: 3,
  },
  {
    id: "src_concentrate",
    name: "Concentrate",
    homepage: "https://concentratemedia.com/",
    feed_url: "https://concentratemedia.com/feed/",
    pull_method: "rss",
    beat_id: "beat_business",
    enabled: true,
    notes: "Verified RSS. Washtenaw / SE Michigan civic and business.",
    lane: "wire",
    place: "Washtenaw",
    weight: 2,
  },
  {
    id: "src_ecurrent",
    name: "Current Magazine",
    homepage: "https://ecurrent.com/",
    feed_url: "https://ecurrent.com/feed/",
    pull_method: "rss",
    beat_id: "beat_arts",
    enabled: true,
    notes: "Verified RSS at ecurrent.com. currentmagazine.com/feed/ is HTML, not RSS.",
    lane: "wire",
    place: "Ann Arbor",
    weight: 1,
  },
  {
    id: "src_waam",
    name: "WAAM 1600",
    homepage: "https://waamradio.com/",
    feed_url: "https://waamradio.com/feed/",
    pull_method: "rss",
    beat_id: "beat_general",
    enabled: true,
    notes: "Verified RSS.",
    lane: "wire",
    place: "Ann Arbor",
    weight: 1,
  },
  {
    id: "src_michigan_public",
    name: "Michigan Public",
    homepage: "https://www.michiganpublic.org/",
    feed_url: "https://www.michiganpublic.org/index.rss",
    pull_method: "rss",
    beat_id: "beat_general",
    enabled: true,
    notes: "Statewide wire — not Washtenaw-filtered. Heavy cap so it does not eat Around town.",
    lane: "wire",
    place: "Washtenaw",
    heavy: true,
    weight: 1,
  },
  {
    id: "src_a2_legistar",
    name: "City of Ann Arbor — Boards & Commissions",
    homepage: "https://www.a2gov.org/city-clerk/boards-and-commissions/",
    feed_url: "https://a2gov.legistar.com/Calendar.aspx",
    pull_method: "html",
    beat_id: "beat_government",
    enabled: true,
    notes:
      "Granicus Legistar HTML. Worker reads printed meeting name, date, clock, and place. Never invent a time. Empty/bot-blocked → Need Traverse News to pull https://a2gov.legistar.com/Calendar.aspx on the live computer → POST /api/desk/civic/import.",
    lane: "civic",
    place: "Ann Arbor",
  },
  {
    id: "src_a2_news",
    name: "City of Ann Arbor — News",
    homepage: "https://www.a2gov.org/",
    feed_url: "https://www.a2gov.org/news/",
    pull_method: "html",
    beat_id: "beat_government",
    enabled: true,
    notes:
      "HTML newsroom, no RSS. Need Traverse News to pull https://www.a2gov.org/news/ on the live computer → POST /api/desk/stories/import. Headline and link only.",
    lane: "wire",
    place: "Ann Arbor",
    family: "official",
  },
  {
    id: "src_washtenaw_calendar",
    name: "Washtenaw County — Calendar",
    homepage: "https://www.washtenaw.org/",
    feed_url: "https://www.washtenaw.org/Calendar.aspx",
    pull_method: "html",
    beat_id: "beat_government",
    enabled: true,
    notes:
      "CivicPlus SPA — ICS paths return HTML, not VCALENDAR. Need Traverse News to pull https://www.washtenaw.org/Calendar.aspx on the live computer → POST /api/desk/civic/import.",
    lane: "civic",
    place: "Washtenaw",
  },
  {
    id: "src_aadl_events",
    name: "Ann Arbor District Library — Events",
    homepage: "https://aadl.org/",
    feed_url: "https://aadl.org/events",
    pull_method: "html",
    beat_id: "beat_events",
    enabled: true,
    notes:
      "HTML events. Legacy api.aadl.org/ical ICS is 404. Need Traverse News to pull https://aadl.org/events on the live computer → POST /api/desk/events/import.",
    lane: "events",
    place: "Ann Arbor",
  },
  {
    id: "src_visit_annarbor",
    name: "Visit Ann Arbor — Events",
    homepage: "https://www.visitannarbor.org/",
    feed_url: "https://www.annarbor.org/events/",
    pull_method: "html",
    beat_id: "beat_events",
    enabled: true,
    notes:
      "Simpleview. Cloud pulls 403. Need Traverse News to pull https://www.annarbor.org/events/ on the live computer → POST /api/desk/events/import. Never invent listings.",
    lane: "events",
    place: "Ann Arbor",
  },
  {
    id: "src_reader_events",
    name: "Reader nights out",
    homepage: "/whats-on",
    feed_url: null,
    pull_method: "none",
    beat_id: "beat_events",
    enabled: true,
    notes:
      "Hand-confirmed reader submissions. Desk confirms one row at a time. Never auto-import.",
    lane: "events",
    place: "Ann Arbor",
  },
  {
    id: "src_a2_police_news",
    name: "Ann Arbor Police — News",
    homepage: "https://www.a2gov.org/police-department/",
    feed_url:
      "https://www.a2gov.org/police-department/community-engagement/news-and-events/",
    pull_method: "html",
    beat_id: "beat_public_safety",
    enabled: true,
    notes:
      "HTML only. Official crashes, outages, closures — never a dump. Need Traverse News to pull the newsroom on the live computer → POST /api/desk/stories/import (source_id src_a2_police_news).",
    lane: "alert",
    place: "Ann Arbor",
  },
  {
    id: "src_washtenaw_press",
    name: "Washtenaw County — Press Releases",
    homepage: "https://www.washtenaw.org/",
    feed_url: "https://www.washtenaw.org/press-releases-0",
    pull_method: "html",
    beat_id: "beat_public_safety",
    enabled: true,
    notes:
      "HTML (includes Sheriff). No CivicAlerts RSS. Official alerts only via POST /api/desk/stories/import. Need Traverse News to pull https://www.washtenaw.org/press-releases-0 on the live computer.",
    lane: "alert",
    place: "Washtenaw",
  },
  {
    id: "src_aaps_cal",
    name: "Ann Arbor Public Schools — Calendar",
    homepage: "https://www.a2schools.org/",
    feed_url:
      "https://calendar.google.com/calendar/ical/aaps.k12.mi.us_bkfpnid9pe5438jl75bschj5k4@group.calendar.google.com/public/basic.ics",
    pull_method: "ics",
    beat_id: "beat_schools",
    enabled: true,
    calendar_url: "https://www.a2schools.org/about-aaps/calendars",
    notes:
      "Verified public Google ICS. Important dates only on /schools — not every listing. Do not invent half days.",
    lane: "school_cal",
    place: "Ann Arbor",
  },
  {
    id: "src_dexter_cal",
    name: "Dexter Community Schools — Calendar",
    homepage: "https://www.dexterschools.org/",
    feed_url: "https://www.dexterschools.org/district/calendar",
    pull_method: "html",
    beat_id: "beat_schools",
    enabled: true,
    calendar_url: "https://www.dexterschools.org/district/calendar",
    notes:
      "Finalsite JS — dcsd.org is the Utah district, do not use it. Need Traverse News to pull https://www.dexterschools.org/district/calendar on the live computer → POST /api/desk/schools/import. Never invent dates.",
    lane: "school_cal",
    place: "Dexter",
  },
  {
    id: "src_pioneer_ath",
    name: "Pioneer HS Athletics",
    homepage: "https://pioneerathletics.arbitersports.com/",
    feed_url: "https://pioneerathletics.arbitersports.com/front",
    pull_method: "html",
    beat_id: "beat_hs_sports",
    enabled: true,
    notes:
      "ArbiterLive JS. Need Traverse News to pull https://pioneerathletics.arbitersports.com/front on the live computer → POST /api/desk/athletics/import. Never invent scores.",
    lane: "athletics",
    place: "Ann Arbor",
  },
  {
    id: "src_skyline_ath",
    name: "Skyline HS Athletics",
    homepage: "https://skylineathletics.arbitersports.com/",
    feed_url: "https://skylineathletics.arbitersports.com/front",
    pull_method: "html",
    beat_id: "beat_hs_sports",
    enabled: true,
    notes:
      "ArbiterLive JS. Need Traverse News to pull https://skylineathletics.arbitersports.com/front on the live computer → POST /api/desk/athletics/import.",
    lane: "athletics",
    place: "Ann Arbor",
  },
  {
    id: "src_huron_ath",
    name: "Huron HS Athletics",
    homepage: "https://huronsports.arbitersports.com/",
    feed_url: "https://huronsports.arbitersports.com/front",
    pull_method: "html",
    beat_id: "beat_hs_sports",
    enabled: true,
    notes:
      "ArbiterLive JS. Need Traverse News to pull https://huronsports.arbitersports.com/front on the live computer → POST /api/desk/athletics/import.",
    lane: "athletics",
    place: "Ann Arbor",
  },
  {
    id: "src_dexter_ath",
    name: "Dexter HS Athletics",
    homepage: "https://dexterathletics.arbitersports.com/",
    feed_url: "https://dexterathletics.arbitersports.com/front",
    pull_method: "html",
    beat_id: "beat_hs_sports",
    enabled: true,
    notes:
      "ArbiterLive JS. Need Traverse News to pull https://dexterathletics.arbitersports.com/front on the live computer → POST /api/desk/athletics/import.",
    lane: "athletics",
    place: "Dexter",
  },
  {
    id: "src_theark",
    name: "The Ark",
    homepage: "https://theark.org/",
    feed_url: "https://theark.org/events/feed/",
    pull_method: "html",
    beat_id: "beat_shows",
    enabled: true,
    notes:
      "Shows lane only. Do not pull this id as events (FALLBACK_SHOWS). Showtimes via POST /api/desk/shows/import — never invent clocks. Coming-up listings use src_ark_events.",
    lane: "shows",
    place: "Ann Arbor",
  },
  {
    id: "src_ark_events",
    name: "The Ark — Events",
    homepage: "https://theark.org/",
    feed_url: "https://theark.org/events/",
    pull_method: "html",
    beat_id: "beat_events",
    enabled: true,
    notes:
      "Worker reads tribe event pages for printed date + Show Starts clock. Never use RSS pubDate (midnight UTC). Empty/bot-blocked → Need Traverse News to pull https://theark.org/events/ on the live computer → POST /api/desk/events/import.",
    lane: "events",
    place: "Ann Arbor",
  },
  {
    id: "src_marquee_arts",
    name: "Marquee Arts (Michigan Theater / State Theatre)",
    homepage: "https://marquee-arts.org/",
    feed_url: "https://marquee-arts.org/feed/",
    pull_method: "rss",
    beat_id: "beat_arts",
    enabled: true,
    notes:
      "Verified RSS of announcements (not a showtime grid). michigantheater.org is hijacked — do not use. Printed film clocks use src_marquee_shows.",
    lane: "wire",
    place: "Ann Arbor",
    weight: 1,
  },
  {
    id: "src_marquee_shows",
    name: "Marquee Arts — Films",
    homepage: "https://marquee-arts.org/",
    feed_url: "https://marquee-arts.org/",
    pull_method: "html",
    beat_id: "beat_shows",
    enabled: true,
    notes:
      "Worker reads homepage film cards with a printed clock (Tuesday, September 1 at 7:00 PM). Now Playing / Opens without a time is skipped — never invent showtimes.",
    lane: "shows",
    place: "Ann Arbor",
  },
  {
    id: "src_marquee_events",
    name: "Marquee Arts — Live",
    homepage: "https://marquee-arts.org/",
    feed_url: "https://marquee-arts.org/",
    pull_method: "html",
    beat_id: "beat_events",
    enabled: true,
    notes:
      "Worker reads homepage live events with printed date + clock (Beth Hart, Swan Lake). Films stay on /shows. Empty/bot-blocked → Need Traverse News to pull https://marquee-arts.org/ on the live computer → POST /api/desk/events/import.",
    lane: "events",
    place: "Ann Arbor",
  },
  {
    id: "src_ums",
    name: "UMS",
    homepage: "https://ums.org/",
    feed_url: "https://ums.org/feed/",
    pull_method: "rss",
    beat_id: "beat_arts",
    enabled: true,
    notes: "Verified RSS of announcements. Showtimes via POST /api/desk/shows/import — never invent clocks.",
    lane: "wire",
    place: "Ann Arbor",
    weight: 1,
  },
  {
    id: "src_ums_events",
    name: "UMS — Season",
    homepage: "https://ums.org/",
    feed_url: "https://ums.org/season/",
    pull_method: "html",
    beat_id: "beat_events",
    enabled: true,
    notes:
      "Worker reads /season/ listing dates only (no printed clock → time_unknown). Never invent showtimes. Empty/bot-blocked → Need Traverse News to pull https://ums.org/season/ on the live computer → POST /api/desk/events/import.",
    lane: "events",
    place: "Ann Arbor",
  },
  {
    id: "src_tn",
    name: "a2.news",
    homepage: "/",
    feed_url: null,
    pull_method: "original",
    beat_id: "beat_original",
    enabled: true,
    notes: "Our desk. Published in full.",
    lane: "original",
    place: "Ann Arbor",
  },
];

export function createAnnArborSeedData(): AppData {
  return {
    beats,
    sources,
    stories: [],
    events: [],
    athletics: [],
    schools: [],
    shows: [],
    subscribers: [],
    unsubscribed: [],
    tips: [],
    event_tips: [],
    last_pull_at: null,
    editions: [],
    email_editions: [],
    drafts: [],
    section_headers: withSectionHeaderSeeds(null),
    page_copy: undefined,
  };
}
