/**
 * Ann Arbor / Washtenaw seed = researched feeds only.
 * NEVER invent Story bodies, events, or showtimes.
 * Browser-blocked calendars stay html/none with a handoff note.
 */
import { withSectionHeaderSeeds } from "@/lib/section-headers";
import type { AppData, Beat, Source } from "@/lib/types";

const beats: Beat[] = [
  { id: "beat_all", name: "All sources", slug: "all", sort: 0 },
  { id: "beat_general", name: "General news", slug: "general-news", sort: 1 },
  { id: "beat_government", name: "Government", slug: "government", sort: 2 },
  { id: "beat_public_safety", name: "Public safety", slug: "public-safety", sort: 3 },
  { id: "beat_schools", name: "Schools", slug: "schools", sort: 4 },
  { id: "beat_transit", name: "Transit", slug: "transit", sort: 5 },
  { id: "beat_events", name: "Events", slug: "events", sort: 6 },
  { id: "beat_shows", name: "Shows", slug: "shows", sort: 7 },
  { id: "beat_arts", name: "Arts", slug: "arts", sort: 8 },
  { id: "beat_business", name: "Business", slug: "business", sort: 9 },
  { id: "beat_social", name: "Social", slug: "social", sort: 10 },
  { id: "beat_sports", name: "Sports", slug: "sports", sort: 11 },
  { id: "beat_hs_sports", name: "High school sports", slug: "high-school-sports", sort: 12 },
  { id: "beat_original", name: "Original", slug: "original", sort: 13 },
];

const sources: Source[] = [
  {
    id: "src_michigandaily",
    name: "Michigan Daily",
    homepage: "https://www.michigandaily.com/",
    feed_url: "https://www.michigandaily.com/feed/",
    pull_method: "rss",
    beat_id: "beat_general",
    enabled: true,
    notes:
      "Verified RSS. Campus + city. Do not add the sports feed — U-M varsity would drown local. City-only section is src_michigandaily_aa.",
    lane: "wire",
    place: "Ann Arbor",
    weight: 2,
  },
  {
    id: "src_michigandaily_news",
    name: "Michigan Daily — News",
    homepage: "https://www.michigandaily.com/",
    feed_url: "https://www.michigandaily.com/news/feed/",
    pull_method: "rss",
    beat_id: "beat_general",
    enabled: true,
    notes: "Verified section RSS.",
    lane: "wire",
    place: "Ann Arbor",
    weight: 2,
  },
  {
    id: "src_michigandaily_aa",
    name: "Michigan Daily — Ann Arbor",
    homepage: "https://www.michigandaily.com/",
    feed_url: "https://www.michigandaily.com/news/ann-arbor/feed/",
    pull_method: "rss",
    beat_id: "beat_general",
    enabled: true,
    notes:
      "Verified city-section RSS (cranes, council, neighborhoods). Not the sports firehose.",
    lane: "wire",
    place: "Ann Arbor",
    weight: 2,
  },
  {
    id: "src_aaobserver",
    name: "Ann Arbor Observer",
    homepage: "https://annarborobserver.com/",
    feed_url: "https://annarborobserver.com/feed/",
    pull_method: "rss",
    beat_id: "beat_general",
    enabled: true,
    notes: "Verified RSS. Do not use observer.com (unrelated NYC publication).",
    lane: "wire",
    place: "Ann Arbor",
    weight: 2,
  },
  {
    id: "src_observer_cal",
    name: "Ann Arbor Observer — Calendar",
    homepage: "https://annarborobserver.com/",
    feed_url: "https://annarborobserver.com/calendar/feed/",
    pull_method: "rss",
    beat_id: "beat_events",
    enabled: true,
    notes:
      "Verified WordPress calendar RSS (headline + permalink). Not a showtime grid. Never invent a clock.",
    lane: "wire",
    place: "Ann Arbor",
    weight: 1,
  },
  {
    id: "src_wemu",
    name: "WEMU 89.1",
    homepage: "https://www.wemu.org/",
    feed_url: "https://www.wemu.org/news.rss",
    pull_method: "rss",
    beat_id: "beat_general",
    enabled: true,
    notes: "Verified news.rss. index.rss is empty — do not use it.",
    lane: "wire",
    place: "Washtenaw",
    weight: 2,
  },
  {
    id: "src_wemu_sports",
    name: "WEMU 89.1 — Sports",
    homepage: "https://www.wemu.org/sports",
    feed_url: "https://www.wemu.org/sports.rss",
    pull_method: "rss",
    beat_id: "beat_sports",
    enabled: true,
    notes:
      "Verified sports.rss. EMU / Washtenaw rec / prep — drop U-M varsity in selectSportsStories. Not a game schedule.",
    lane: "wire",
    place: "Washtenaw",
    weight: 2,
  },
  {
    id: "src_suntimes",
    name: "The Sun Times News",
    homepage: "https://thesuntimesnews.com/",
    feed_url: "https://thesuntimesnews.com/feed/",
    pull_method: "rss",
    beat_id: "beat_general",
    enabled: true,
    notes:
      "Dexter / Chelsea / Saline weeklies. Reserved suburb Around slots when the headline names the town.",
    lane: "wire",
    place: "Dexter",
    weight: 3,
  },
  {
    id: "src_saline_summit",
    name: "Saline Summit News",
    homepage: "https://salinesummit.substack.com/",
    feed_url: "https://salinesummit.substack.com/feed",
    pull_method: "rss",
    beat_id: "beat_general",
    enabled: true,
    notes: "Verified Substack RSS. Saline civic and school board. Reserved Saline Around slots.",
    lane: "wire",
    place: "Saline",
    weight: 2,
  },
  {
    id: "src_washtenaw_voice",
    name: "Washtenaw Voice",
    homepage: "https://www.washtenawvoice.com/",
    feed_url: "https://www.washtenawvoice.com/feed/",
    pull_method: "rss",
    beat_id: "beat_general",
    enabled: true,
    notes: "Verified RSS. WCC student paper — Ypsilanti / county, not U-M varsity.",
    lane: "wire",
    place: "Ypsilanti",
    weight: 1,
  },
  {
    id: "src_concentrate",
    name: "Concentrate",
    homepage: "https://concentratemedia.com/",
    feed_url: "https://concentratemedia.com/feed/",
    pull_method: "rss",
    beat_id: "beat_business",
    enabled: true,
    notes: "Verified RSS. Washtenaw / SE Michigan civic and business.",
    lane: "wire",
    place: "Washtenaw",
    weight: 2,
  },
  {
    id: "src_ecurrent",
    name: "Current Magazine",
    homepage: "https://ecurrent.com/",
    feed_url: "https://ecurrent.com/feed/",
    pull_method: "rss",
    beat_id: "beat_arts",
    enabled: true,
    notes: "Verified RSS at ecurrent.com. currentmagazine.com/feed/ is HTML, not RSS.",
    lane: "wire",
    place: "Ann Arbor",
    weight: 1,
  },
  {
    id: "src_waam",
    name: "WAAM 1600",
    homepage: "https://waamradio.com/",
    feed_url: "https://waamradio.com/feed/",
    pull_method: "rss",
    beat_id: "beat_general",
    enabled: true,
    notes: "Verified RSS.",
    lane: "wire",
    place: "Ann Arbor",
    weight: 1,
  },
  {
    id: "src_michigan_public",
    name: "Michigan Public",
    homepage: "https://www.michiganpublic.org/",
    feed_url: "https://www.michiganpublic.org/index.rss",
    pull_method: "rss",
    beat_id: "beat_general",
    enabled: true,
    notes: "Statewide wire — not Washtenaw-filtered. Heavy cap so it does not eat Around town.",
    lane: "wire",
    place: "Washtenaw",
    heavy: true,
    weight: 1,
  },
  {
    id: "src_a2_legistar",
    name: "City of Ann Arbor — Boards & Commissions",
    homepage: "https://www.a2gov.org/city-clerk/boards-and-commissions/",
    feed_url: "https://a2gov.legistar.com/Calendar.aspx",
    pull_method: "html",
    beat_id: "beat_government",
    enabled: true,
    notes:
      "Granicus Legistar HTML. Worker reads printed meeting name, date, clock, and place. Never invent a time. Empty/bot-blocked → Need Traverse News to pull https://a2gov.legistar.com/Calendar.aspx on the live computer → POST /api/desk/civic/import.",
    lane: "civic",
    place: "Ann Arbor",
  },
  {
    id: "src_a2_news",
    name: "City of Ann Arbor — News",
    homepage: "https://www.a2gov.org/",
    feed_url: "https://www.a2gov.org/news/",
    pull_method: "html",
    beat_id: "beat_government",
    enabled: true,
    notes:
      "Worker reads newsroom cards (headline, permalink, printed date). No invented dek. Empty/bot-blocked → Need Traverse News to pull https://www.a2gov.org/news/ on the live computer → POST /api/desk/stories/import.",
    lane: "wire",
    place: "Ann Arbor",
    family: "official",
  },
  {
    id: "src_washtenaw_calendar",
    name: "Washtenaw County — Calendar",
    homepage: "https://www.washtenaw.org/",
    feed_url: "https://washtenawcomi.api.civicclerk.com/v1/Events",
    pull_method: "html",
    beat_id: "beat_government",
    enabled: true,
    notes:
      "Worker reads CivicClerk OData /Events (printed startDateTime + place). Portal: https://washtenawcomi.portal.civicclerk.com. Empty/bot-blocked → Need Traverse News to pull the portal on the live computer → POST /api/desk/civic/import.",
    lane: "civic",
    place: "Washtenaw",
  },
  {
    id: "src_aadl_events",
    name: "Ann Arbor District Library — Events",
    homepage: "https://aadl.org/",
    feed_url: "https://aadl.org/events-feed/upcoming",
    pull_method: "html",
    beat_id: "beat_events",
    enabled: true,
    notes:
      "Worker reads Drupal upcoming cards (title, /node/ permalink, printed clock, branch). Legacy api.aadl.org/ical is 404. Empty/bot-blocked → Need Traverse News to pull https://aadl.org/events-feed/upcoming on the live computer → POST /api/desk/events/import.",
    lane: "events",
    place: "Ann Arbor",
  },
  {
    id: "src_visit_annarbor",
    name: "Visit Ann Arbor — Events",
    homepage: "https://www.visitannarbor.org/",
    feed_url: "https://www.annarbor.org/events/",
    pull_method: "html",
    beat_id: "beat_events",
    enabled: true,
    notes:
      "Simpleview. Cloud pulls 403. Need Traverse News to pull https://www.annarbor.org/events/ on the live computer → POST /api/desk/events/import. Never invent listings.",
    lane: "events",
    place: "Ann Arbor",
  },
  {
    id: "src_reader_events",
    name: "Reader nights out",
    homepage: "/whats-on",
    feed_url: null,
    pull_method: "none",
    beat_id: "beat_events",
    enabled: true,
    notes:
      "Hand-confirmed reader submissions. Desk confirms one row at a time. Never auto-import.",
    lane: "events",
    place: "Ann Arbor",
  },
  {
    id: "src_a2_police_news",
    name: "Ann Arbor Police — News",
    homepage: "https://www.a2gov.org/police-department/",
    feed_url:
      "https://www.a2gov.org/police-department/community-engagement/news-and-events/",
    pull_method: "html",
    beat_id: "beat_public_safety",
    enabled: true,
    notes:
      "HTML only. Official crashes, outages, closures — never a dump. Need Traverse News to pull the newsroom on the live computer → POST /api/desk/stories/import (source_id src_a2_police_news).",
    lane: "alert",
    place: "Ann Arbor",
  },
  {
    id: "src_washtenaw_press",
    name: "Washtenaw County — Press Releases",
    homepage: "https://www.washtenaw.org/",
    feed_url: "https://www.washtenaw.org/press-releases-0",
    pull_method: "html",
    beat_id: "beat_public_safety",
    enabled: true,
    notes:
      "HTML (includes Sheriff). No CivicAlerts RSS. Official alerts only via POST /api/desk/stories/import. Need Traverse News to pull https://www.washtenaw.org/press-releases-0 on the live computer.",
    lane: "alert",
    place: "Washtenaw",
  },
  {
    id: "src_ypsi_news",
    name: "City of Ypsilanti — News",
    homepage: "https://www.cityofypsilanti.com/",
    feed_url:
      "https://www.cityofypsilanti.com/RSSFeed.aspx?ModID=1&CID=City-of-Ypsilanti-News-1",
    pull_method: "rss",
    beat_id: "beat_government",
    enabled: true,
    notes: "Verified CivicEngage News Flash RSS. Official notices — headline + permalink only.",
    lane: "wire",
    place: "Ypsilanti",
    family: "official",
  },
  {
    id: "src_saline_news",
    name: "City of Saline — News",
    homepage: "https://www.salinemi.gov/",
    feed_url: "https://www.salinemi.gov/rss.xml",
    pull_method: "rss",
    beat_id: "beat_government",
    enabled: true,
    notes:
      "Verified city RSS. Item links are relative (_T2_R###.php) — pull resolves against salinemi.gov. Official family.",
    lane: "wire",
    place: "Saline",
    family: "official",
  },
  {
    id: "src_chelsea_news",
    name: "City of Chelsea — News",
    homepage: "https://www.city-chelsea.org/",
    feed_url: "https://www.city-chelsea.org/rss.xml",
    pull_method: "rss",
    beat_id: "beat_government",
    enabled: true,
    notes:
      "Verified city RSS. Item links are relative (news_detail_T2_R###.php) — pull resolves against city-chelsea.org.",
    lane: "wire",
    place: "Chelsea",
    family: "official",
  },
  {
    id: "src_aaps_cal",
    name: "Ann Arbor Public Schools — Calendar",
    homepage: "https://www.a2schools.org/",
    feed_url:
      "https://calendar.google.com/calendar/ical/aaps.k12.mi.us_bkfpnid9pe5438jl75bschj5k4@group.calendar.google.com/public/basic.ics",
    pull_method: "ics",
    beat_id: "beat_schools",
    enabled: true,
    calendar_url: "https://www.a2schools.org/about-aaps/calendars",
    notes:
      "Verified public Google ICS. Important dates only on /schools — not every listing. Do not invent half days.",
    lane: "school_cal",
    place: "Ann Arbor",
  },
  {
    id: "src_dexter_cal",
    name: "Dexter Community Schools — Calendar",
    homepage: "https://www.dexterschools.org/",
    feed_url:
      "https://www.dexterschools.org/fs/calendar-manager/events.ics?feed_id=977c1f9c-1d06-4690-a0cb-bfb5db5460a5",
    pull_method: "ics",
    beat_id: "beat_schools",
    enabled: true,
    calendar_url: "https://www.dexterschools.org/district/calendar",
    notes:
      "Finalsite public ICS (district + no-school + half-day calendars on the list-view page). Important dates only on /schools — not open houses or board meetings. dcsd.org is the Utah district, do not use it. Never invent dates.",
    lane: "school_cal",
    place: "Dexter",
  },
  {
    id: "src_ycs_cal",
    name: "Ypsilanti Community Schools — Calendar",
    homepage: "https://www.ycschools.us/",
    feed_url: "https://www.ycschools.us/for-parents/calendar/",
    pull_method: "html",
    beat_id: "beat_schools",
    enabled: true,
    calendar_url: "https://www.ycschools.us/for-parents/calendar/",
    notes:
      "Finalsite/Apptegy HTML — no public ICS on the parents calendar. Need Traverse News to pull https://www.ycschools.us/for-parents/calendar/ on the live computer → POST /api/desk/schools/import. Important dates only. Never invent dates.",
    lane: "school_cal",
    place: "Ypsilanti",
  },
  {
    id: "src_saline_cal",
    name: "Saline Area Schools — Calendar",
    homepage: "https://www.salineschools.org/",
    feed_url:
      "https://calendar.google.com/calendar/ical/saline.k12.mi.us_tsbl8qslkk5cv66m75m4js4it4%40group.calendar.google.com/public/basic.ics",
    pull_method: "ics",
    beat_id: "beat_schools",
    enabled: true,
    calendar_url: "https://www.salineschools.org/district-resources/calendar/",
    notes:
      "Verified public Google ICS from the district calendar embed. Important dates only on /schools — schoolItemsFromEvents drops board meetings and concerts. Never invent dates.",
    lane: "school_cal",
    place: "Saline",
  },
  {
    id: "src_chelsea_cal",
    name: "Chelsea School District — Calendar",
    homepage: "https://www.chelseaschools.org/",
    feed_url: "https://www.chelseaschools.org/about-us/calendar",
    pull_method: "html",
    beat_id: "beat_schools",
    enabled: true,
    calendar_url: "https://www.chelseaschools.org/about-us/calendar",
    notes:
      "Finalsite calendar page exists; public events.ics feed_id returned 0 VEVENTs from the Worker. Need Traverse News to pull https://www.chelseaschools.org/about-us/calendar on the live computer → POST /api/desk/schools/import. Important dates only.",
    lane: "school_cal",
    place: "Chelsea",
  },
  {
    id: "src_lincoln_cal",
    name: "Lincoln Consolidated Schools — Calendar",
    homepage: "https://www.lincolnk12.org/",
    feed_url:
      "https://thrillshare-cmsv2.services.thrillshare.com/api/v4/o/29131/cms/events/generate_ical?filter_ids&section_ids",
    pull_method: "ics",
    beat_id: "beat_schools",
    enabled: true,
    calendar_url: "https://www.lincolnk12.org/events",
    notes:
      "Verified Thrillshare public ICS (LCS no-school dates). Important dates only on /schools — BOE meetings drop. South of Ypsilanti. Never invent dates.",
    lane: "school_cal",
    place: "Washtenaw",
  },
  {
    id: "src_pioneer_ath",
    name: "Pioneer HS Athletics",
    homepage: "https://pioneerathletics.net/",
    feed_url: "https://pioneerathletics.net/Events",
    pull_method: "html",
    beat_id: "beat_hs_sports",
    enabled: true,
    notes:
      "EventLink /Events table (printed date + clock, or TBD → time_unknown). ArbiterLive is dead. Never invent kickoff. Do not use websites.eventlink.com/s/skyline-high-school — that is Idaho.",
    lane: "athletics",
    place: "Ann Arbor",
  },
  {
    id: "src_skyline_ath",
    name: "Skyline HS Athletics",
    homepage: "https://skylineathletics.arbitersports.com/",
    feed_url: "https://skylineathletics.arbitersports.com/front",
    pull_method: "html",
    beat_id: "beat_hs_sports",
    enabled: true,
    notes:
      "ArbiterLive /front is InvalidSite from the Worker (2026-09). Need Traverse News to find the current Skyline athletics page → POST /api/desk/athletics/import.",
    lane: "athletics",
    place: "Ann Arbor",
  },
  {
    id: "src_huron_ath",
    name: "Huron HS Athletics",
    homepage: "https://huronsports.arbitersports.com/",
    feed_url: "https://huronsports.arbitersports.com/front",
    pull_method: "html",
    beat_id: "beat_hs_sports",
    enabled: true,
    notes:
      "ArbiterLive /front is InvalidSite from the Worker (2026-09). Need Traverse News to find the current Huron athletics page → POST /api/desk/athletics/import.",
    lane: "athletics",
    place: "Ann Arbor",
  },
  {
    id: "src_dexter_ath",
    name: "Dexter HS Athletics",
    homepage: "https://websites.eventlink.com/s/dexterathletics/",
    feed_url: "https://websites.eventlink.com/s/dexterathletics/Events",
    pull_method: "html",
    beat_id: "beat_hs_sports",
    enabled: true,
    notes:
      "EventLink /Events table (printed EDT clock or TBD). ArbiterLive is dead. Never invent kickoff.",
    lane: "athletics",
    place: "Dexter",
  },
  {
    id: "src_ypsi_ath",
    name: "Ypsilanti HS Athletics",
    homepage: "https://www.ypsigrizzlies.com/",
    feed_url: "https://www.ypsigrizzlies.com/",
    pull_method: "html",
    beat_id: "beat_hs_sports",
    enabled: true,
    notes:
      "Ypsi Grizzlies site is JS. Need Traverse News to pull https://www.ypsigrizzlies.com/ on the live computer → POST /api/desk/athletics/import. Never invent scores.",
    lane: "athletics",
    place: "Ypsilanti",
  },
  {
    id: "src_saline_ath",
    name: "Saline HS Athletics",
    homepage: "https://salinehornets.com/",
    feed_url: "https://websites.eventlink.com/s/saline/Events",
    pull_method: "html",
    beat_id: "beat_hs_sports",
    enabled: true,
    notes:
      "EventLink /Events table (printed EDT clock or TBD). BigTeams calendar is JS. Never invent kickoff.",
    lane: "athletics",
    place: "Saline",
  },
  {
    id: "src_chelsea_ath",
    name: "Chelsea HS Athletics",
    homepage: "https://chelseabulldogs.org/",
    feed_url: "https://chelseabulldogs.org/Events",
    pull_method: "html",
    beat_id: "beat_hs_sports",
    enabled: true,
    notes:
      "EventLink /Events table (printed EDT clock or TBD). Never invent kickoff.",
    lane: "athletics",
    place: "Chelsea",
  },
  {
    id: "src_milan_ath",
    name: "Milan HS Athletics",
    homepage: "https://milanbigreds.org/",
    feed_url: "https://milanbigreds.org/Events",
    pull_method: "html",
    beat_id: "beat_hs_sports",
    enabled: true,
    notes:
      "EventLink /Events table (printed EDT clock or TBD). Do not use websites.eventlink.com/s/milan — that is Milan, Indiana (Lawrenceburg / Jac-Cen-Del). Never invent kickoff.",
    lane: "athletics",
    place: "Washtenaw",
  },
  {
    id: "src_theark",
    name: "The Ark",
    homepage: "https://theark.org/",
    feed_url: "https://theark.org/events/feed/",
    pull_method: "html",
    beat_id: "beat_shows",
    enabled: true,
    notes:
      "Shows lane only. Do not pull this id as events (FALLBACK_SHOWS). Showtimes via POST /api/desk/shows/import — never invent clocks. Coming-up listings use src_ark_events.",
    lane: "shows",
    place: "Ann Arbor",
  },
  {
    id: "src_ark_events",
    name: "The Ark — Events",
    homepage: "https://theark.org/",
    feed_url: "https://theark.org/events/",
    pull_method: "html",
    beat_id: "beat_events",
    enabled: true,
    notes:
      "Worker reads tribe event pages for printed date + Show Starts clock. Never use RSS pubDate (midnight UTC). Empty/bot-blocked → Need Traverse News to pull https://theark.org/events/ on the live computer → POST /api/desk/events/import.",
    lane: "events",
    place: "Ann Arbor",
  },
  {
    id: "src_marquee_arts",
    name: "Marquee Arts (Michigan Theater / State Theatre)",
    homepage: "https://marquee-arts.org/",
    feed_url: "https://marquee-arts.org/feed/",
    pull_method: "rss",
    beat_id: "beat_arts",
    enabled: true,
    notes:
      "Verified RSS of announcements (not a showtime grid). michigantheater.org is hijacked — do not use. Printed film clocks use src_marquee_shows.",
    lane: "wire",
    place: "Ann Arbor",
    weight: 1,
  },
  {
    id: "src_marquee_shows",
    name: "Marquee Arts — Films",
    homepage: "https://marquee-arts.org/",
    feed_url: "https://marquee-arts.org/",
    pull_method: "html",
    beat_id: "beat_shows",
    enabled: true,
    notes:
      "Worker reads homepage film cards with a printed clock (Tuesday, September 1 at 7:00 PM). Now Playing / Opens without a time is skipped — never invent showtimes.",
    lane: "shows",
    place: "Ann Arbor",
  },
  {
    id: "src_marquee_events",
    name: "Marquee Arts — Live",
    homepage: "https://marquee-arts.org/",
    feed_url: "https://marquee-arts.org/",
    pull_method: "html",
    beat_id: "beat_events",
    enabled: true,
    notes:
      "Worker reads homepage live events with printed date + clock (Beth Hart, Swan Lake). Films stay on /shows. Empty/bot-blocked → Need Traverse News to pull https://marquee-arts.org/ on the live computer → POST /api/desk/events/import.",
    lane: "events",
    place: "Ann Arbor",
  },
  {
    id: "src_ums",
    name: "UMS",
    homepage: "https://ums.org/",
    feed_url: "https://ums.org/feed/",
    pull_method: "rss",
    beat_id: "beat_arts",
    enabled: true,
    notes: "Verified RSS of announcements. Showtimes via POST /api/desk/shows/import — never invent clocks.",
    lane: "wire",
    place: "Ann Arbor",
    weight: 1,
  },
  {
    id: "src_ums_shows",
    name: "UMS — Shows",
    homepage: "https://ums.org/",
    feed_url: "https://ums.org/season/",
    pull_method: "html",
    beat_id: "beat_shows",
    enabled: true,
    notes:
      "Filled from src_ums_events listing dates (time_unknown). Never invent a curtain. Browser clocks → POST /api/desk/shows/import.",
    lane: "shows",
    place: "Ann Arbor",
  },
  {
    id: "src_encore_shows",
    name: "The Encore Theatre — Shows",
    homepage: "https://theencoretheatre.org/",
    feed_url: "https://theencoretheatre.org/wp-json/tribe/events/v1/events?per_page=50",
    pull_method: "html",
    beat_id: "beat_shows",
    enabled: true,
    notes:
      "Verified Tribe REST. Production run windows only (12:01 AM is not a curtain). time_unknown. Printed clocks → POST /api/desk/shows/import. Dexter.",
    lane: "shows",
    place: "Dexter",
  },
  {
    id: "src_ums_events",
    name: "UMS — Season",
    homepage: "https://ums.org/",
    feed_url: "https://ums.org/season/",
    pull_method: "html",
    beat_id: "beat_events",
    enabled: true,
    notes:
      "Worker reads /season/ listing dates only (no printed clock → time_unknown). Never invent showtimes. Empty/bot-blocked → Need Traverse News to pull https://ums.org/season/ on the live computer → POST /api/desk/events/import.",
    lane: "events",
    place: "Ann Arbor",
  },
  {
    id: "src_chelsea_update",
    name: "Chelsea Update",
    homepage: "https://chelseaupdate.com/",
    feed_url: "https://chelseaupdate.com/feed/",
    pull_method: "rss",
    beat_id: "beat_general",
    enabled: true,
    notes: "Verified WordPress RSS. Chelsea civic desk. Reserved Chelsea Around slots.",
    lane: "wire",
    place: "Chelsea",
    weight: 2,
  },
  {
    id: "src_chelseamich",
    name: "Chelsea Michigan",
    homepage: "https://chelseamich.com/",
    feed_url: "https://chelseamich.com/feed",
    pull_method: "rss",
    beat_id: "beat_events",
    enabled: true,
    notes: "Verified RSS of Chelsea community events (Hometown Holiday, Chocolate Extravaganza).",
    lane: "wire",
    place: "Chelsea",
    weight: 1,
  },
  {
    id: "src_wemu_arts",
    name: "WEMU 89.1 — Arts",
    homepage: "https://www.wemu.org/arts",
    feed_url: "https://www.wemu.org/arts.rss",
    pull_method: "rss",
    beat_id: "beat_arts",
    enabled: true,
    notes: "Verified arts.rss. Do not use business.rss — last items are 2013 pledge-drive leftovers.",
    lane: "wire",
    place: "Washtenaw",
    weight: 1,
  },
  {
    id: "src_dexter_news",
    name: "City of Dexter — News",
    homepage: "https://www.dextermi.gov/",
    feed_url: "https://www.dextermi.gov/rss.xml",
    pull_method: "rss",
    beat_id: "beat_government",
    enabled: true,
    notes: "Verified CivicEngage RSS. Official notices — headline + permalink only.",
    lane: "wire",
    place: "Dexter",
    family: "official",
  },
  {
    id: "src_pittsfield_news",
    name: "Pittsfield Township — News",
    homepage: "https://www.pittsfield-mi.gov/",
    feed_url:
      "https://www.pittsfield-mi.gov/RSSFeed.aspx?ModID=1&CID=News-Flash-1",
    pull_method: "rss",
    beat_id: "beat_government",
    enabled: true,
    notes: "Verified CivicEngage News Flash RSS. Between Ann Arbor and Saline.",
    lane: "wire",
    place: "Pittsfield",
    family: "official",
  },
  {
    id: "src_superior_news",
    name: "Superior Township — News",
    homepage: "https://superiortownship.org/",
    feed_url: "https://superiortownship.org/feed/",
    pull_method: "rss",
    beat_id: "beat_government",
    enabled: true,
    notes: "Verified WordPress RSS. Official notices east of Ypsilanti.",
    lane: "wire",
    place: "Washtenaw",
    family: "official",
  },
  {
    id: "src_spark",
    name: "Ann Arbor SPARK",
    homepage: "https://annarborusa.org/",
    feed_url: "https://annarborusa.org/feed/",
    pull_method: "rss",
    beat_id: "beat_business",
    enabled: true,
    notes: "Verified RSS. Regional economic-development desk.",
    lane: "wire",
    place: "Ann Arbor",
    weight: 1,
  },
  {
    id: "src_wcrc",
    name: "Washtenaw County Road Commission",
    homepage: "https://www.wcroads.org/",
    feed_url: "https://www.wcroads.org/feed/",
    pull_method: "rss",
    beat_id: "beat_government",
    enabled: true,
    notes: "Verified RSS. Printed road closures and reopenings only.",
    lane: "wire",
    place: "Washtenaw",
    family: "official",
  },
  {
    id: "src_theride",
    name: "TheRide — News",
    homepage: "https://www.theride.org/",
    feed_url: "https://www.theride.org/about/news",
    pull_method: "html",
    beat_id: "beat_transit",
    enabled: true,
    notes:
      "Worker reads /about/news teasers (headline, permalink, printed month day year). Never invent a holiday schedule. Empty/bot-blocked → Need Traverse News to pull https://www.theride.org/about/news on the live computer → POST /api/desk/stories/import.",
    lane: "wire",
    place: "Washtenaw",
    family: "official",
  },
  {
    id: "src_ydl",
    name: "Ypsilanti District Library",
    homepage: "https://www.ypsilibrary.org/",
    feed_url: "https://www.ypsilibrary.org/feed/",
    pull_method: "rss",
    beat_id: "beat_events",
    enabled: true,
    notes: "Verified WordPress RSS of library news (closures, collections).",
    lane: "wire",
    place: "Ypsilanti",
    weight: 1,
  },
  {
    id: "src_saline_lib",
    name: "Saline District Library",
    homepage: "https://www.salinelibrary.org/",
    feed_url: "https://www.salinelibrary.org/feed/",
    pull_method: "rss",
    beat_id: "beat_events",
    enabled: true,
    notes: "Verified WordPress RSS.",
    lane: "wire",
    place: "Saline",
    weight: 1,
  },
  {
    id: "src_dexter_lib",
    name: "Dexter District Library",
    homepage: "https://www.dexter.lib.mi.us/",
    feed_url: "https://www.dexter.lib.mi.us/feed/",
    pull_method: "rss",
    beat_id: "beat_events",
    enabled: true,
    notes: "Verified WordPress RSS.",
    lane: "wire",
    place: "Dexter",
    weight: 1,
  },
  {
    id: "src_purple_rose",
    name: "Purple Rose Theatre",
    homepage: "https://www.purplerosetheatre.org/",
    feed_url: "https://www.purplerosetheatre.org/feed/",
    pull_method: "rss",
    beat_id: "beat_arts",
    enabled: true,
    notes:
      "Verified RSS of announcements (programs, Santa photos) — not a showtime grid. Showtimes stay browser import → POST /api/desk/shows/import.",
    lane: "wire",
    place: "Chelsea",
    weight: 1,
  },
  {
    id: "src_avalon",
    name: "Avalon Housing",
    homepage: "https://www.avalonhousing.org/",
    feed_url: "https://www.avalonhousing.org/feed/",
    pull_method: "rss",
    beat_id: "beat_general",
    enabled: true,
    notes: "Verified RSS. Ypsilanti / Ann Arbor housing nonprofit — not a listing dump.",
    lane: "wire",
    place: "Ypsilanti",
    weight: 1,
  },
  {
    id: "src_pulp",
    name: "Pulp",
    homepage: "https://pulp.aadl.org/",
    feed_url: "https://aadl.org/pulp/feed",
    pull_method: "rss",
    beat_id: "beat_arts",
    enabled: true,
    notes:
      "Verified AADL Pulp RSS (concerts, visual art, One Track Mind). Arts desk — not a showtime grid.",
    lane: "wire",
    place: "Ann Arbor",
    weight: 2,
  },
  {
    id: "src_aa_family",
    name: "Ann Arbor Family",
    homepage: "https://annarborfamily.com/",
    feed_url: "https://annarborfamily.com/feed/",
    pull_method: "rss",
    beat_id: "beat_general",
    enabled: true,
    notes: "Verified RSS. Family / AAPS civic. Not a listing dump.",
    lane: "wire",
    place: "Ann Arbor",
    weight: 1,
  },
  {
    id: "src_artcenter",
    name: "Ann Arbor Art Center",
    homepage: "https://www.annarborartcenter.org/",
    feed_url: "https://www.annarborartcenter.org/feed/",
    pull_method: "rss",
    beat_id: "beat_arts",
    enabled: true,
    notes: "Verified RSS of exhibitions and artist notes.",
    lane: "wire",
    place: "Ann Arbor",
    weight: 1,
  },
  {
    id: "src_ozone",
    name: "Ozone House",
    homepage: "https://ozonehouse.org/",
    feed_url: "https://ozonehouse.org/feed/",
    pull_method: "rss",
    beat_id: "beat_general",
    enabled: true,
    notes: "Verified RSS. Ypsilanti / Ann Arbor youth-housing nonprofit.",
    lane: "wire",
    place: "Ypsilanti",
    weight: 1,
  },
  {
    id: "src_riverside",
    name: "Riverside Arts Center",
    homepage: "https://riversidearts.org/",
    feed_url: "https://riversidearts.org/feed/",
    pull_method: "rss",
    beat_id: "beat_arts",
    enabled: true,
    notes:
      "Verified RSS of Ypsilanti workshops and gallery notes — not a showtime grid.",
    lane: "wire",
    place: "Ypsilanti",
    weight: 1,
  },
  {
    id: "src_tn",
    name: "a2.news",
    homepage: "/",
    feed_url: null,
    pull_method: "original",
    beat_id: "beat_original",
    enabled: true,
    notes: "Our desk. Published in full.",
    lane: "original",
    place: "Ann Arbor",
  },
];

export function createAnnArborSeedData(): AppData {
  return {
    beats,
    sources,
    stories: [],
    events: [],
    athletics: [],
    schools: [],
    shows: [],
    subscribers: [],
    unsubscribed: [],
    tips: [],
    event_tips: [],
    last_pull_at: null,
    editions: [],
    email_editions: [],
    drafts: [],
    section_headers: withSectionHeaderSeeds(null),
    page_copy: undefined,
  };
}
