import type { Source } from "@/lib/types";
import type { SourceMeta } from "@/lib/sites/types";

/** Lane / ranking flags for the Traverse catalog. Applied on seed + KV merge. */
export const TRAVERSE_SOURCE_META: Record<string, SourceMeta> = {
  src_ticker: { lane: "wire", place: "Traverse City", weight: 2, family: "eyes-only" },
  src_ticker_cal: { lane: "events", place: "Traverse City" },
  src_re: { lane: "wire", place: "Traverse City", paywalled: true },
  src_ipr: { lane: "wire", place: "Traverse City", weight: 2 },
  src_910: { lane: "wire", place: "Traverse City", weight: 2, heavy: true },
  src_northern: { lane: "wire", place: "Traverse City", weight: 2, family: "eyes-only" },
  src_tcbn: { lane: "wire", place: "Traverse City", weight: 2, family: "eyes-only" },
  src_overheard: { lane: "wire", place: "Traverse City" },
  src_gt_cal: { lane: "civic", place: "Traverse City" },
  src_city_news: { lane: "wire", place: "Traverse City", family: "official" },
  src_upnorth: { lane: "wire", place: "Traverse City", family: "upnorth", heavy: true },
  src_leelanau_ent: { lane: "wire", place: "Leelanau", weight: 2 },
  src_omp_gazette: { lane: "wire", place: "Old Mission", weight: 2 },
  src_glenarbor_sun: { lane: "wire", place: "Glen Arbor", weight: 2 },
  src_elk_news: { lane: "wire", place: "Elk Rapids", weight: 2 },
  src_benzie_rp: { lane: "wire", place: "Benzie", weight: 2 },
  src_betsie: { lane: "wire", place: "Benzie", weight: 2 },
  src_antrim_review: { lane: "wire", place: "Antrim", weight: 2 },
  src_leelanau_co: { lane: "civic", place: "Leelanau", family: "official" },
  src_gtb: { lane: "wire", place: "Peshawbestown", family: "official" },
  src_civicweb: { lane: "civic", place: "Traverse City" },
  src_connect: { lane: "wire", place: "Traverse City" },
  src_visit: { lane: "wire", place: "Traverse City" },
  src_visit_events: { lane: "events", place: "Traverse City" },
  src_reader_events: { lane: "events", place: "Traverse City" },
  src_tart: { lane: "events", place: "Traverse City" },
  src_tcaps: { lane: "events", place: "Traverse City" },
  src_tbaisd: { lane: "events", place: "Traverse City" },
  src_downtown: { lane: "events", place: "Traverse City" },
  src_opera: { lane: "events", place: "Traverse City" },
  src_tcphil: { lane: "events", place: "Traverse City" },
  src_interlochen: { lane: "events", place: "Interlochen" },
  src_tadl: { lane: "events", place: "Traverse City" },
  src_dennos: { lane: "events", place: "Traverse City" },
  src_oldtown: { lane: "shows", place: "Traverse City" },
  src_city_opera: { lane: "shows", place: "Traverse City" },
  src_state_theatre: { lane: "shows", place: "Traverse City" },
  src_bay_theatre: { lane: "shows", place: "Suttons Bay" },
  src_elk_cinema: { lane: "shows", place: "Elk Rapids" },
  src_amc_cherry: { lane: "shows", place: "Traverse City" },
  src_pride: { lane: "events", place: "Traverse City" },
  src_cherry: { lane: "events", place: "Traverse City" },
  src_bata: { lane: "alert", place: "Traverse City" },
  src_nws: { lane: "events", place: "Traverse City" },
  src_gt911: { lane: "alert", place: "Traverse City" },
  src_ticker_fb: { lane: "alert", place: "Traverse City" },
  src_910_sports: { lane: "wire", place: "Traverse City", weight: 2 },
  src_re_sports: { lane: "wire", place: "Traverse City", paywalled: true },
  src_re_prep: { lane: "wire", place: "Traverse City", paywalled: true },
  src_tcc_ath: { lane: "athletics", place: "Traverse City" },
  src_tcw_ath: { lane: "athletics", place: "Traverse City" },
  src_tcsf_ath: { lane: "athletics", place: "Traverse City" },
  src_tcch_ath: { lane: "athletics", place: "Traverse City" },
  src_elk_ath: { lane: "athletics", place: "Elk Rapids" },
  src_suttons_ath: { lane: "athletics", place: "Suttons Bay" },
  src_leland_ath: { lane: "athletics", place: "Leland" },
  src_glenlake_ath: { lane: "athletics", place: "Glen Lake" },
  src_kingsley_ath: { lane: "athletics", place: "Kingsley" },
  src_benzie_ath: { lane: "athletics", place: "Benzie" },
  src_frankfort_ath: { lane: "athletics", place: "Frankfort" },
  src_kalkaska_ath: { lane: "athletics", place: "Kalkaska" },
  src_forest_ath: { lane: "athletics", place: "Forest Area" },
  src_mancelona_ath: { lane: "athletics", place: "Mancelona" },
  src_buckley_ath: { lane: "athletics", place: "Buckley" },
  src_northport_ath: { lane: "athletics", place: "Northport" },
  src_centrallake_ath: { lane: "athletics", place: "Central Lake" },
  src_tcaps_cal: { lane: "school_cal", place: "Traverse City" },
  src_gtacs_cal: { lane: "school_cal", place: "Traverse City" },
  src_gta_cal: { lane: "school_cal", place: "Traverse City" },
  src_elk_cal: { lane: "school_cal", place: "Elk Rapids" },
  src_suttons_cal: { lane: "school_cal", place: "Suttons Bay" },
  src_leland_cal: { lane: "school_cal", place: "Leland" },
  src_glenlake_cal: { lane: "school_cal", place: "Glen Lake" },
  src_kingsley_cal: { lane: "school_cal", place: "Kingsley" },
  src_tcch_cal: { lane: "school_cal", place: "Traverse City" },
  src_tn: { lane: "original", place: "Traverse City" },
};

export function applySourceMeta(
  source: Source,
  meta: Record<string, SourceMeta> = TRAVERSE_SOURCE_META,
): Source {
  const extra = meta[source.id];
  if (!extra) return source;
  return {
    ...source,
    lane: source.lane ?? extra.lane,
    place: source.place ?? extra.place,
    weight: source.weight ?? extra.weight,
    paywalled: source.paywalled ?? extra.paywalled,
    family: source.family ?? extra.family,
    heavy: source.heavy ?? extra.heavy,
  };
}
